INTERNAL_AWARD_CATEGORY = "dynamic-score-internal"
INTERNAL_AWARD_NAME = "Dynamic score adjustment"

DEFAULT_TARGET_PERCENT = 0.20
MIN_TARGET_PERCENT = 0.05
MAX_TARGET_PERCENT = 1.00
MIN_TARGET_SOLVES = 5
